import Head from "next/head";
import Image from "next/image";
// import { Inter } from 'next/font/google'
import styles from "../styles/Home.module.css";
import { useEffect, useRef, useState } from "react";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [products, setProducts] = useState<
  //   { id: string; properties: { id: string }[] }[]
  // >([]);
  const [products, setProducts] = useState<{ id: string; name: string }[]>([]);
  // useEffect(() => {
  //   fetch("/api/get-items")
  //     .then((res) => res.json())
  //     .then((data) => setProducts(data.items));
  // }, []);
  useEffect(() => {
    fetch("/api/get-products")
      .then((res) => res.json())
      .then((data) => setProducts(data.items));
  }, []);
  const inputRef = useRef<HTMLInputElement>(null);
  const handleClick = () => {
    if (inputRef.current === null || inputRef.current.value === "") {
      alert("name을 입력해주세요.");
    }
    fetch(`/api/add-item?name=${inputRef.current?.value}`)
      .then((res) => res.json())
      .then(
        (data) => alert(data.message)
        //  console.log(data)
      );
    // .then((res) => console.log(res));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <div className={styles.description}>
        <p>
          Get started by editing&nbsp;
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <input ref={inputRef} type="text" placeholder="name" />
        <button onClick={handleClick}>Add jaket</button>
        <div>
          <p>Product List</p>
          {products &&
            products.map((item) => <div key={item.id}>{item.name}</div>)}
          {/* {products &&
            products.map((item) => (
              <div key={item.id}>
                {JSON.stringify(item)}
                {item?.properties &&
                  Object.entries(item.properties).map(([key, value]) => (
                    <button
                      key={key}
                      onClick={() => {
                        fetch(
                          `/api/get-detail?pageId=${item.id}&propertyId=${value.id}`
                        )
                          .then((res) => res.json())
                          .then((data) => alert(JSON.stringify(data.detail)));
                      }}
                    >
                      {key}
                    </button>
                  ))}
                <br />
                <br />
              </div>
            ))} */}
        </div>
      </div>
      {console.log(products)}
      {/* </main> */}
    </>
  );
}
