/** @jsxImportSource @emotion/react */

import Head from "next/head";
import Image from "next/image";
// import { Inter } from 'next/font/google'
import styles from "../styles/Home.module.css";
import { useEffect, useRef, useState } from "react";
import { css } from "@emotion/react";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [products, setProducts] = useState<
  //   { id: string; properties: { id: string }[] }[]
  // >([]);
  const [products, setProducts] = useState<
    { id: string; name: string; createdAt: string }[]
  >([]);
  // useEffect(() => {
  //   fetch("/api/get-items")
  //     .then((res) => res.json())
  //     .then((data) => setProducts(data.items));
  // }, []);
  useEffect(() => {
    fetch("/api/get-products")
      .then((res) => res.json())
      .then(
        (data) => setProducts(data.items)
        // console.log(data.items)
      );
  }, []);
  const inputRef = useRef<HTMLInputElement>(null);
  const handleClick = () => {
    if (inputRef.current === null || inputRef.current.value === "") {
      alert("name을 입력해주세요.");
    } else {
      fetch(`/api/add-item?name=${inputRef.current?.value}`)
        .then((res) => res.json())
        .then(
          (data) => alert(data.message)
          //  console.log(data)
        );
      // .then((res) => console.log(res));
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <div className={styles.description}>
        <p>
          Get started by editing&nbsp;
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <input
          className="placeholder:italic placeholder:text-slate-400 block bg-white w-96 border border-slate-300 rounded-md py-2 pl-3 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm"
          placeholder="Search for anything..."
          type="text"
          name="search"
          ref={inputRef}
        />
        <button
          css={css`
            padding: 32px;
            background-color: hotpink;
            font-size: 24px;
            border-radius: 4px;
          `}
          onClick={handleClick}
        >
          Add jaket
        </button>
        <div>
          <p>Product List</p>
          {products &&
            products.map((item) => (
              <>
                <div key={item.id}>{item.name}</div>
                <span>{item.createdAt}</span>
                <br />
                <br />
              </>
            ))}

          {/* {products &&
            products.map((item) => (
              <div key={item.id}>
                {JSON.stringify(item)}
                {item?.properties &&
                  Object.entries(item.properties).map(([key, value]) => (
                    <button
                      key={key}
                      onClick={() => {
                        fetch(
                          `/api/get-detail?pageId=${item.id}&propertyId=${value.id}`
                        )
                          .then((res) => res.json())
                          .then((data) => alert(JSON.stringify(data.detail)));
                      }}
                    >
                      {key}
                    </button>
                  ))}
                <br />
                <br />
              </div>
            ))} */}
        </div>
      </div>
      {/* {console.log(products)} */}
      {/* </main> */}
      {/* <Image
        width={300}
        height={300}
        alt="img"
        src="https://as2.ftcdn.net/v2/jpg/05/44/69/13/1000_F_544691377_60BJEfTNlQvKCKADBzeVweCvGI3VOoi8.jpg"
      ></Image> */}
    </>
  );
}
